import type { Metadata } from "next";
import { SiteFrame } from "../../components/SiteFrame";
import { earlierBuilds } from "../../site-data";

export const metadata: Metadata = { title: "代表项目 — 赵文茜", description: "做过的项目，解决过的问题。", openGraph: { title: "代表项目 — 赵文茜", description: "做过的事，以及它们为什么值得做。", images: [] }, twitter: { card: "summary", title: "代表项目 — 赵文茜", description: "做过的事，以及它们为什么值得做。", images: [] } };
const projects = [
  { number: "01", company: "蚂蚁集团 · 2026.04 — 2026.07", title: "LLaDA：数据与推理", summary: "160 万条开源 SFT 数据里为什么会出现 loss spike？我从数据诊断入手，也尝试把推理蒸馏用到扩散语言模型上，并继续追问数据分布和推理策略之间的关系。", result: "目标分布实验中，代码和数学 benchmark 提升 3%–5%。", mark: "∿", tone: "violet" },
  { number: "02", company: "蚂蚁集团 · 2025.12 — 2026.01", title: "让医疗模型记住用户", summary: "“记住一个人”很难直接验对错。我把它拆成 34 个具体场景，再用 must / optional / overthink 三类标准告诉模型：什么必须记住，什么不必多想。", result: "最终产出 10,000+ 组用于 RL 的 Query–Rubric 数据。", mark: "✣", tone: "peach" },
  { number: "03", company: "MINIMAX · 2025.03 — 2025.07", title: "MiniMax-M2 的预训练数据", summary: "面对 TB 级 Common Crawl，先定义什么是好数据，再让多标签 reward model 去判断。之后用消融实验寻找质量、领域和采样比例之间更合适的平衡。", result: "AUC > 0.95；多个 benchmark 提升 5%–10%。", mark: "◎", tone: "green" },
];
export default function ChineseWorkPage() { return <SiteFrame active="WORK" locale="zh"><section className="pageIntro"><p className="eyebrow">03 / 代表项目</p><h1>做过的事，<br /><em>和为什么要做。</em></h1><p>比起堆技术名词，我更想讲清楚：当时遇到了什么问题，我怎么拆开它，最后又改变了什么。</p></section><section className="caseSection"><div className="sectionRail"><span>职业项目</span><span>01 — 03</span></div><div className="caseGrid">{projects.map((project) => <article className={`caseCard ${project.tone}`} key={project.title}><div className="caseMeta"><span>{project.number}</span><span>{project.company}</span></div><i aria-hidden="true">{project.mark}</i><h2>{project.title}</h2><p>{project.summary}</p><strong>{project.result}</strong></article>)}</div></section><section className="buildSection"><div><p className="sectionNumber">B / 更早以前</p><h2>那时，大模型<br /><em>还不是主角。</em></h2></div><div className="buildList">{earlierBuilds.map((item, index) => <a href={item.href} target="_blank" rel="noreferrer" key={item.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{item.title}</h3><p>{item.meta}</p></div><span>↗</span></a>)}</div></section></SiteFrame>; }
